[project]
name = "chessrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "backoff~=2.2",
    "chess~=1.11",
    "ipykernel>=7.3.0",
    "numpy>=2.5.2",
    "pyyaml~=6.0",
    "requests~=2.34",
    "rich~=15.0",
    "torch>=2.13.0",
]
